version: '3.7'

services:
  db-v2:
    image: "postgres:12.0-alpine"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data/
  web-v2:
    build: .
    image: messageboard-app-v2
    command: gunicorn messageboardapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static-volume:/static
    #expose:
      #- 8088 #expose will hide the 8088 port from outside the docker container
    ports:
      - 8000:8000  #8088(left of colon) is exposed to outside the docker container
    env_file:
      - ./.env
    depends_on:
      - db-v2
  #nginx:
    #build: ./nginx
    #image: messageboard-nginx-v2
    #ports:
      #- 1338:80  #8088 will be exposed to outside the docker container
    #volumes:
      #- static-volume:/static
    #depends_on:
      #- web
volumes:
  postgres-data:
  static-volume: