version: '3.7'

services:
  db:
    image: "postgres:12.0-alpine"
    env_file:
      - ./.env
    ports:
      - "5432:5432"
    volumes: 
      - postgres-data:/var/lib/postgresql/data/
  web:
    build: .
    command: gunicorn messageboardapp.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - static-volume:/static
    expose:
      - 8000 
    env_file:
      - ./.env
    depends_on:
      - db
  nginx:
    build: ./nginx
    ports:
      - 1338:80
    volumes:
      - static-volume:/static
    depends_on:
      - web
volumes:
  postgres-data:
  static-volume: